/*
 * FNXC:ComputerUse 2026-08-11-03:54:
 * Values are passed through argv or stdin rather than interpolated into this source. OS automation
 * receives untrusted app names, window IDs, and locator paths, so keeping this program static is
 * the injection boundary.
 */
export const MACOS_PERMISSION_PREFLIGHT = `ObjC.import('ApplicationServices'); ObjC.import('CoreGraphics'); ObjC.bindFunction('AXIsProcessTrusted', ['bool', []]); ObjC.bindFunction('CGPreflightScreenCaptureAccess', ['bool', []]); function run(argv) { return JSON.stringify({accessibility: Boolean($.AXIsProcessTrusted()), screenRecording: Boolean($.CGPreflightScreenCaptureAccess())}); }`;

/** System Events operations; argv is [operation, ...parameters] and is never source-interpolated. */
export const MACOS_AUTOMATION = `
ObjC.import('Foundation');
ObjC.import('CoreGraphics');
function text(v) { try { return String(v); } catch (_) { return ''; } }
function nullable(getter) { try { var v = getter(); return v === undefined ? null : v; } catch (_) { return null; } }
function appRef(p) { return { bundleId: nullable(function(){ return p.bundleIdentifier(); }), name: text(p.name()), pid: Number(p.unixId()) }; }
function allApps(se) { var ps = se.applicationProcesses(); var out=[]; for (var i=0;i<ps.length;i++) { try { out.push(appRef(ps[i])); } catch (_) {} } return out; }
function processFor(se, raw) { var ps=se.applicationProcesses(); for (var i=0;i<ps.length;i++) { var p=ps[i]; var id=nullable(function(){return p.bundleIdentifier();}); if (text(p.name())===raw || id===raw || ('pid:'+String(p.unixId()))===raw) return p; } throw new Error('app-not-found'); }
function rect(v) { if (!v || v.length < 4) return null; return {x:Number(v[0]),y:Number(v[1]),width:Number(v[2]),height:Number(v[3])}; }
function sameBounds(a,b) { var frame=ObjC.unwrap(b); return a && frame && Math.abs(a.x-Number(frame.X))<2 && Math.abs(a.y-Number(frame.Y))<2 && Math.abs(a.width-Number(frame.Width))<2 && Math.abs(a.height-Number(frame.Height))<2; }
function captureWindowId(p,title,bounds) { try { var options=1|16, rows=$.CGWindowListCopyWindowInfo(options,0), pid=Number(p.unixId()), match=null; for(var i=0;i<rows.count;i++) { var row=rows.objectAtIndex(i), owner=Number(ObjC.unwrap(row.objectForKey('kCGWindowOwnerPID'))), name=String(ObjC.unwrap(row.objectForKey('kCGWindowName')) || ''), frame=row.objectForKey('kCGWindowBounds'); if(owner===pid && name===title && sameBounds(bounds, frame)) { if(match!==null) return null; match=Number(ObjC.unwrap(row.objectForKey('kCGWindowNumber'))); } } return match; } catch (_) {} return null; }
function windowsFor(p) { var ws=p.windows(), out=[]; for(var i=0;i<ws.length;i++) { var w=ws[i], position=nullable(function(){return w.position();}), size=nullable(function(){return w.size();}), bounds=position&&size?{x:Number(position[0]),y:Number(position[1]),width:Number(size[0]),height:Number(size[1])}:null, title=text(nullable(function(){return w.name();})); out.push({windowId: String(nullable(function(){return w.id();}) || i), windowIndex:i, title:title, bounds:bounds, minimized:Boolean(nullable(function(){return w.attributes.byName('AXMinimized').value();})), captureWindowId:captureWindowId(p,title,bounds)}); } return out; }
function windowFor(p, id, index) { var ws=p.windows(); for(var i=0;i<ws.length;i++) { var w=ws[i], current=String(nullable(function(){return w.id();}) || i); if ((id && current===id) || (!id && index!=='' && i===Number(index)) || (!id && index==='' && i===0)) return w; } throw new Error('window-not-found'); }
function children(el) { try { return el.uiElements(); } catch (_) { return []; } }
function role(el) { return text(nullable(function(){return el.role();})); }
function elementValue(el) { return nullable(function(){ return text(el.value()); }); }
function attrs(el, path) { var r=role(el), sub=nullable(function(){return text(el.subrole());}), ident=nullable(function(){return text(el.identifier());}), title=nullable(function(){return text(el.name());}), pos=nullable(function(){return el.position();}), size=nullable(function(){return el.size();}), actions=[]; try { var as=el.actions(); for(var i=0;i<as.length;i++) actions.push(text(as[i].name())); } catch (_) {} return {role:r,title:title,value:elementValue(el),label:nullable(function(){return text(el.description());}),enabled:!Boolean(nullable(function(){return el.attributes.byName('AXEnabled').value();})===false),focused:Boolean(nullable(function(){return el.attributes.byName('AXFocused').value();})),bounds:pos&&size?{x:Number(pos[0]),y:Number(pos[1]),width:Number(size[0]),height:Number(size[1])}:null,actions:actions,locator:{kind:'ax-path',path:path,role:r,subrole:sub,identifier:ident,title:title}}; }
function capture(w) { var elements=[], lines=[], count=0, truncated=false, max=500, depthMax=12; function walk(el,path,depth) { if(count>=max||depth>depthMax){truncated=true;return;} var a=attrs(el,path); a.index=count++; elements.push(a); lines.push(path+' '+a.role+(a.title?' '+a.title:'')); var cs=children(el); for(var i=0;i<cs.length;i++) walk(cs[i],path+'/'+role(cs[i])+'['+i+']',depth+1); } walk(w,'window[0]',0); return {treeText:lines.join('\n'),elements:elements,truncated:truncated}; }
function resolve(w,path) { var parts=String(path).split('/'); var el=w; for(var i=1;i<parts.length;i++){ var m=/^(.*)\\[(\\d+)\\]$/.exec(parts[i]); if(!m) throw new Error('locator-not-found'); var cs=children(el), n=Number(m[2]); if(n>=cs.length || role(cs[n])!==m[1]) throw new Error('locator-not-found'); el=cs[n]; } return attrs(el,path); }
function focused(p) { try { return p.attributes.byName('AXFocusedUIElement').value(); } catch (_) { throw new Error('no-focused-element'); } }
function stdin() { var d=$.NSFileHandle.fileHandleWithStandardInput.readDataToEndOfFile; return ObjC.unwrap($.NSString.alloc.initWithDataEncoding(d,$.NSUTF8StringEncoding)); }
function scrollKeyCode(direction) { if(direction==='up') return 126; if(direction==='down') return 125; if(direction==='left') return 123; if(direction==='right') return 124; throw new Error('invalid-scroll-direction'); }
function perform(p,w,path,kind,arg) { var el=path ? resolve(w,path) : null; if(kind==='click') { el.actions.byName('AXPress').perform(); } else if(kind==='set-value') { el.value = stdin(); } else if(kind==='type-text') { el=el||focused(p); try { el.attributes.byName('AXFocused').value=true; } catch (_) {} Application('System Events').keystroke(stdin()); } else if(kind==='press-key') { el=el||focused(p); try { el.attributes.byName('AXFocused').value=true; } catch (_) {} Application('System Events').keystroke(arg); } else if(kind==='scroll') { el=el||focused(p); if(!el) throw new Error('no-focused-element'); var n=Number(arg.split(':')[1]); var keyCode=scrollKeyCode(arg.split(':')[0]); Application('System Events').keyCode(keyCode,{using:['option']}); for(var i=1;i<n;i++) Application('System Events').keyCode(keyCode,{using:['option']}); } else if(kind==='drag') { throw new Error('drag-requires-coordinate-event'); } return true; }
/* FNXC:ComputerUse 2026-08-11-04:12: System Events has no mouseMove/mouseDown/mouseUp API. Drag must post the real CoreGraphics down, dragged, and up events so this advertised action never becomes a silent scripting no-op. */
function postMouse(type, x, y) { var event=$.CGEventCreateMouseEvent(null,type,$.CGPointMake(x,y),0); if(!event) throw new Error('cg-event-create-failed'); $.CGEventPost(0,event); }
function dragCoordinates(_se, fromX, fromY, toX, toY) { var values=[Number(fromX),Number(fromY),Number(toX),Number(toY)]; for(var i=0;i<values.length;i++) if(!isFinite(values[i])) throw new Error('invalid-drag-coordinate'); postMouse(1,values[0],values[1]); postMouse(6,values[2],values[3]); postMouse(2,values[2],values[3]); }
function run(argv) { var se=Application('System Events'), op=argv[0]; if(op==='list-apps') return JSON.stringify({apps:allApps(se)}); var p=processFor(se,argv[1]); if(op==='list-windows') return JSON.stringify({windows:windowsFor(p)}); if(op==='hotkey'){ se.keystroke(argv[2],{using:argv.slice(3)}); return JSON.stringify({ok:true}); } if(op==='drag-coordinates'){ dragCoordinates(se,argv[2],argv[3],argv[4],argv[5]); return JSON.stringify({ok:true}); } var w=windowFor(p,argv[2],argv[3]); if(op==='state') return JSON.stringify(capture(w)); if(op==='resolve-locator') return JSON.stringify({element:resolve(w,argv[4])}); if(op==='restore-window'){ try { w.attributes.byName('AXMinimized').value=false; } catch (_) {} return JSON.stringify({ok:true}); } return JSON.stringify({ok:perform(p,w,argv[4],op,argv[5])}); }
`;
