/*
FNXC:HumanPlanApproval 2026-09-15-06:24:
FN-408 — single source of truth for the per-card human plan decision.

Requirement (original French request): a card created with the human-approval toggle must, AFTER the
plan and its Plan Review, wait for an operator decision before entering execution. Reject re-plans
the card carrying the operator message; Approve releases execution carrying the operator note.

Design invariants encoded here, because every gate (triage, hold release, execution entry, promote,
expedite, restart recovery) must agree on exactly one predicate:

1. `approvedPlanFingerprint` is NOT human proof. Triage's auto-approved spec-lock path and the graph's
   Plan Review persistence both write it. Human proof must additionally carry an operator-authored
   decision from the approve-plan route.
2. Proof is scoped to BOTH the decided plan (`planFingerprint`) and the review episode
   (`planningEpisodeId`). A rejected plan regenerated byte-identically keeps its fingerprint, so the
   episode is what makes the stale approval unusable.
3. Absent/malformed/stale proof closes the gate (fail closed). Simply arming the option never blocks
   the planner or the reviewer — only the release into execution.
*/

import type { Task } from "../types.js";
import type { HumanPlanApprovalDecision, HumanPlanApprovalState } from "../types/task/task-core.js";
import type { WorkflowStepResult } from "../types/workflow/workflow-steps.js";
import { isPlanReviewSatisfied } from "./plan-approval.js";
import { PLAN_REVIEW_GROUP_ID } from "../workflows/builtin-plan-review-group.js";

/** Durable `awaitingApprovalReason` marker distinguishing this hold from the revision-cap park. */
export const HUMAN_PLAN_APPROVAL_REASON = "human-plan-approval" as const;

/** Maximum accepted operator message length, enforced server-side before persistence. */
export const HUMAN_PLAN_APPROVAL_MESSAGE_MAX_LENGTH = 10_000;

export type HumanPlanApprovalTask = Pick<Task, "humanPlanApproval" | "workflowStepResults" | "approvedPlanFingerprint">;

/** True when this card carries the explicit per-card requirement. */
export function isHumanPlanApprovalEnabled(task: Pick<Task, "humanPlanApproval"> | undefined | null): boolean {
  return task?.humanPlanApproval?.enabled === true;
}

/*
Episode identity is the completion stamp of the CURRENT satisfied Plan Review result. Respecify and
reject supersede that result, so the next review necessarily produces a new stamp. Falling back
through startedAt/attemptAt keeps adapters that omit completedAt usable while still refusing a
result carrying no usable stamp at all.
*/
export function resolvePlanReviewEpisodeId(
  results: readonly WorkflowStepResult[] | undefined,
): string | undefined {
  const satisfied = results?.filter(isPlanReviewSatisfied) ?? [];
  if (satisfied.length === 0) return undefined;
  const current = satisfied[satisfied.length - 1];
  const stamp = current.completedAt ?? current.startedAt;
  return typeof stamp === "string" && stamp.trim().length > 0 ? stamp.trim() : undefined;
}

/** The decision that would be current for this task's plan, or undefined when none is usable. */
export function resolveCurrentHumanPlanApprovalDecision(
  task: HumanPlanApprovalTask | undefined | null,
): HumanPlanApprovalDecision | undefined {
  if (!isHumanPlanApprovalEnabled(task)) return undefined;
  const decision = task?.humanPlanApproval?.decision;
  if (!decision || typeof decision !== "object") return undefined;
  const episodeId = resolvePlanReviewEpisodeId(task?.workflowStepResults);
  if (!episodeId || decision.planningEpisodeId !== episodeId) return undefined;
  const fingerprint = task?.approvedPlanFingerprint;
  if (!fingerprint || decision.planFingerprint !== fingerprint) return undefined;
  return decision;
}

/** True when a current, plan- and episode-matched operator APPROVAL exists. */
export function hasCurrentHumanPlanApproval(task: HumanPlanApprovalTask | undefined | null): boolean {
  return resolveCurrentHumanPlanApprovalDecision(task)?.decision === "approved";
}

/**
 * The shared execution gate: an armed card with no current approval must never enter execution.
 * This deliberately returns true while Plan Review is still unsatisfied too, so a stop between
 * review persistence and status publication cannot open a release window.
 */
export function isHumanPlanApprovalPending(task: HumanPlanApprovalTask | undefined | null): boolean {
  if (!isHumanPlanApprovalEnabled(task)) return false;
  return !hasCurrentHumanPlanApproval(task);
}

/**
 * FN-408's EXECUTION-ENTRY fence, kept deliberately separate from `isTaskBlockedOnApproval`
 * (merge/task-merge.ts), which also guards planning continuation dispatch: folding the per-card
 * requirement into that predicate would stop the planner and reviewer from ever producing the plan
 * the operator is supposed to validate. It also stays in THIS module because task-merge's exports
 * reach the dashboard's browser bundle, which cannot load this module's `node:crypto` dependency.
 */
export function isTaskBlockedOnHumanPlanApproval(task: HumanPlanApprovalTask | undefined | null): boolean {
  return isHumanPlanApprovalPending(task);
}

/** True when the card is armed, its Plan Review is satisfied, and the operator has not decided yet. */
export function isHumanPlanApprovalDecidable(task: HumanPlanApprovalTask | undefined | null): boolean {
  if (!isHumanPlanApprovalEnabled(task)) return false;
  if (!resolvePlanReviewEpisodeId(task?.workflowStepResults)) return false;
  if (!task?.approvedPlanFingerprint) return false;
  return !hasCurrentHumanPlanApproval(task);
}

/** The operator note attached to the CURRENT approval, for injection into implementation prompts. */
export function resolveApprovedHumanPlanNote(task: HumanPlanApprovalTask | undefined | null): string | undefined {
  const decision = resolveCurrentHumanPlanApprovalDecision(task);
  if (decision?.decision !== "approved") return undefined;
  const message = decision.message?.trim();
  return message && message.length > 0 ? message : undefined;
}

export class HumanPlanApprovalMessageError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "HumanPlanApprovalMessageError";
  }
}

/**
 * Normalize an operator message. Whitespace-only input is treated as "no message" rather than an
 * error, because both decisions accept an empty note. The text is stored and rendered as text only.
 */
export function sanitizeHumanPlanApprovalMessage(input: unknown): string | undefined {
  if (input === undefined || input === null) return undefined;
  if (typeof input !== "string") throw new HumanPlanApprovalMessageError("message must be a string");
  const trimmed = input.trim();
  if (trimmed.length === 0) return undefined;
  if (trimmed.length > HUMAN_PLAN_APPROVAL_MESSAGE_MAX_LENGTH) {
    throw new HumanPlanApprovalMessageError(
      `message must be at most ${HUMAN_PLAN_APPROVAL_MESSAGE_MAX_LENGTH} characters`,
    );
  }
  return trimmed;
}

/**
 * Creation accepts ONLY the armed flag. A client-supplied decision is dropped so task creation can
 * never manufacture release proof; duplication keeps the intent and drops any inherited decision.
 */
export function buildHumanPlanApprovalCreationState(enabled: unknown): HumanPlanApprovalState | undefined {
  if (enabled === true) return { enabled: true };
  if (typeof enabled === "object" && enabled !== null && (enabled as HumanPlanApprovalState).enabled === true) {
    return { enabled: true };
  }
  return undefined;
}

/** Heading used by every implementation prompt so the note is recognizable and greppable. */
export const HUMAN_PLAN_APPROVAL_NOTE_HEADING = "## Operator Note From Plan Approval";

/**
 * FNXC:HumanPlanApproval 2026-09-15-06:24:
 * FN-408 — THE single formatter shared by the standard, Fast, per-step, and reduced-step prompt
 * builders, so the approved note reads identically in every session shape and cannot drift.
 *
 * Only the note of the CURRENT decision is emitted: a note approved for a superseded plan or a
 * previous review episode must never leak into a later implementation. The note is implementation
 * CONTEXT, not a plan edit — it is never written into PROMPT.md and therefore never changes the plan
 * fingerprint. Returns an empty string when there is nothing to say, so callers add no blank section.
 */
export function formatApprovedHumanPlanNoteSection(task: HumanPlanApprovalTask | undefined | null): string {
  const note = resolveApprovedHumanPlanNote(task);
  if (!note) return "";
  return [
    HUMAN_PLAN_APPROVAL_NOTE_HEADING,
    "",
    "An operator approved this plan and asked you to keep the following in mind while implementing it.",
    "It is additional context, not a replacement for the plan above.",
    "",
    note,
  ].join("\n");
}

export class HumanPlanApprovalWorkflowError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "HumanPlanApprovalWorkflowError";
  }
}

/**
 * FNXC:HumanPlanApproval 2026-09-15-06:24:
 * FN-408 — the per-card requirement is meaningless without a Plan Review to validate, so arming it
 * forces the standard Plan Review group into the effective step selection even when Fast execution
 * cleared that selection. When the chosen workflow genuinely offers no compatible plan review, the
 * combination is refused at creation rather than producing a card that can never be validated; the
 * alternative (inventing an out-of-graph reviewer) is explicitly out of scope.
 *
 * `planReviewAvailable: undefined` means "could not be determined" and is treated as available: the
 * release gate still fails closed, so an undetectable workflow never silently releases work.
 */
export function resolveHumanPlanApprovalWorkflowSteps(
  enabled: boolean,
  steps: string[] | undefined,
  options: { planReviewAvailable?: boolean } = {},
): string[] | undefined {
  if (!enabled) return steps;
  if (options.planReviewAvailable === false) {
    throw new HumanPlanApprovalWorkflowError(
      "Human plan approval requires a workflow that runs Plan Review before execution",
    );
  }
  if (steps === undefined) return steps;
  return steps.includes(PLAN_REVIEW_GROUP_ID) ? steps : [...steps, PLAN_REVIEW_GROUP_ID];
}

/*
FNXC:HumanPlanApproval 2026-09-15-07:30:
FN-408 remediation — Fast execution and the per-card human requirement are mutually exclusive, and
the REQUIREMENT wins. Fast is planless by construction: `resolveFastLaneRoute` bypasses every
pre-merge optional group (plan review included) and the planning seam nodes whatever the step
selection says, and triage excludes Fast cards from planning candidates. An armed Fast card would
therefore never produce a plan, never satisfy Plan Review, never publish `awaiting-approval`, and
the approve/reject route would refuse every decision for lack of a review episode — an immobilized
card with no operator recourse.

So arming the requirement NEUTRALIZES `executionMode: "fast"` at the single place the row is
written (creation and update), turning the card back into an ordinary planned card. Refusing the
combination outright was the alternative; neutralizing keeps the operator's stronger intent ("I want
to validate this plan") instead of failing their create. Cards that are not armed keep Fast exactly
as before.
*/
export function resolveHumanPlanApprovalExecutionMode<T>(
  enabled: boolean,
  executionMode: T,
): T | undefined {
  if (enabled && executionMode === "fast") return undefined;
  return executionMode;
}

/**
 * Reset / respecify / duplication keep the per-card requirement but invalidate the decision, so a
 * regenerated plan always asks again. Returns `null` when nothing is armed, matching the store's
 * explicit clear sentinel.
 */
export function clearHumanPlanApprovalDecision(
  state: HumanPlanApprovalState | undefined,
): HumanPlanApprovalState | null {
  if (state?.enabled !== true) return null;
  return { enabled: true };
}
