import { docConceptNodeId, edgeId, type ExtractorInput, type ExtractorOutput, type GraphNode } from "./graph-types.js";
import { markdownHtmlCommentUnits } from "./extract-fnxc.js";
const slug=(s:string)=>s.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"heading";
export function extractMarkdown(input:ExtractorInput):ExtractorOutput{const nodes:GraphNode[]=[];const edges:ExtractorOutput["edges"]=[], stack:{level:number;node:GraphNode}[]=[];const counts=new Map<string,number>();const htmlRanges=markdownHtmlCommentUnits(input.content).map(unit=>[unit.pos,unit.pos+unit.text.length] as const);let fence:{marker:string;length:number}|undefined, previousIndented=false, previousBlank=true,offset=0;for(const [i,line] of input.content.split(/\r?\n/).entries()){const trim=line.trim(), fenceMatch=/^(`{3,}|~{3,})/.exec(trim);/*
FNXC:KnowledgeGraph 2026-08-10-11:54:
A markdown HTML comment may open after the line's first character. Range overlap keeps every
heading on that comment-bearing line out of the doc-concept graph.
*/
const inHtml=htmlRanges.some(([start,end])=>start<offset+line.length&&end>offset);if(!inHtml&&fenceMatch){if(!fence)fence={marker:fenceMatch[0]![0]!,length:fenceMatch[0]!.length};else if(fence.marker===fenceMatch[0]![0]&&fenceMatch[0]!.length>=fence.length&&trim===fenceMatch[0])fence=undefined;offset+=line.length+1;previousIndented=false;previousBlank=false;continue;}const indented: boolean=/^(?: {4}|\t)/.test(line)&&(previousIndented||previousBlank);if(fence||inHtml||indented){offset+=line.length+1;previousIndented=indented;previousBlank=line.trim()==="";continue;}const match=/^(#{1,6})\s+(.+?)\s*#*\s*$/.exec(line);if(!match){offset+=line.length+1;previousIndented=false;previousBlank=line.trim()==="";continue;}const level=match[1]!.length,name=match[2]!, key=slug(name),index=counts.get(key)??0;counts.set(key,index+1);const node:GraphNode={id:docConceptNodeId(input.relPath,key,index),kind:"doc-concept",name,owner:"file",ownerPath:input.relPath,source:{path:input.relPath,line:i+1,column:line.indexOf("#")+1},attributes:{headingLevel:String(level)}};nodes.push(node);while(stack.length&&stack.at(-1)!.level>=level)stack.pop();const parent=stack.at(-1)?.node;edges.push({id:edgeId("contains",parent?.id??input.fileNodeId,node.id),kind:"contains",from:parent?.id??input.fileNodeId,to:node.id,provenance:"extracted",owner:"file",ownerPath:input.relPath,source:node.source,attributes:{}});stack.push({level,node});offset+=line.length+1;previousIndented=false;previousBlank=line.trim()==="";}return{nodes,edges,importRefs:[]};}
