// GENERATED by scripts/gen-cli-catalogs.mjs — do not edit by hand.
// Run `pnpm --filter @fusion/i18n gen:cli-catalogs` to regenerate.
import en_common from "../locales/en/common.json";
import en_cli from "../locales/en/cli.json";
import en_errors from "../locales/en/errors.json";
import es_common from "../locales/es/common.json";
import es_cli from "../locales/es/cli.json";
import es_errors from "../locales/es/errors.json";
import fr_common from "../locales/fr/common.json";
import fr_cli from "../locales/fr/cli.json";
import fr_errors from "../locales/fr/errors.json";
import ko_common from "../locales/ko/common.json";
import ko_cli from "../locales/ko/cli.json";
import ko_errors from "../locales/ko/errors.json";
import pt_BR_common from "../locales/pt-BR/common.json";
import pt_BR_cli from "../locales/pt-BR/cli.json";
import pt_BR_errors from "../locales/pt-BR/errors.json";
import zh_CN_common from "../locales/zh-CN/common.json";
import zh_CN_cli from "../locales/zh-CN/cli.json";
import zh_CN_errors from "../locales/zh-CN/errors.json";
import zh_TW_common from "../locales/zh-TW/common.json";
import zh_TW_cli from "../locales/zh-TW/cli.json";
import zh_TW_errors from "../locales/zh-TW/errors.json";

export const cliResources = {
  "en": {
    common: en_common,
    cli: en_cli,
    errors: en_errors,
  },
  "es": {
    common: es_common,
    cli: es_cli,
    errors: es_errors,
  },
  "fr": {
    common: fr_common,
    cli: fr_cli,
    errors: fr_errors,
  },
  "ko": {
    common: ko_common,
    cli: ko_cli,
    errors: ko_errors,
  },
  "pt-BR": {
    common: pt_BR_common,
    cli: pt_BR_cli,
    errors: pt_BR_errors,
  },
  "zh-CN": {
    common: zh_CN_common,
    cli: zh_CN_cli,
    errors: zh_CN_errors,
  },
  "zh-TW": {
    common: zh_TW_common,
    cli: zh_TW_cli,
    errors: zh_TW_errors,
  },
} as const;
